#!/bin/bash

function testSystemIsEc2() {
  # one of these two tests will fail.
  assertFalse "system isn't an ec2 instance" "systemIsEc2"
  assertTrue "system is an ec2 instance" "systemIsEc2"
}

function testSystemGetMeta() {
  if systemIsEc2; then
    assertTrue "when there is no instance id, it should get one" "systemGetMeta instance-id"
    INSTANCE_ID=`systemGetMeta instance-id`
  else
    INSTANCE_ID="i-ffffffff"
  fi

  assertTrue "should get instance-id of ec2 instance" "systemGetMeta instance-id"
  assertTrue "should be an instance id" "echo $INSTANCE_ID | egrep '^i-[0-9a-f]{8}$'"
}

function testSystemCleanUp() {
  systemCleanUp
  assertFalse "ELB_TMP_FILE should be deleted" "[ -f $ELB_TMP_FILE ]"
  assertFalse "AS_TMP_FILE should be deleted" "[ -f $AS_TMP_FILE ]"
}


function oneTimeSetUp() {
  # load include to test
  source ../lib/system.inc
  ELB_TMP_FILE=`mktemp -t XXXXXX`
  AS_TMP_FILE=`mktemp -t XXXXXX`
}

function SetUp() {
  unset IS_EC2
  unset INSTANCE_ID
  unset AMI_ID
}

function oneTimeTearDown() {
  echo "== details"
  echo "instance: $INSTANCE_ID"
}

# load and run shUnit2
source ./shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
