#! /bin/bash -i
shopt -s expand_aliases

testSystemIsEc2() {
  # one of these two tests will fail.
  assertFalse "system isn't an ec2 instance" "systemIsEc2"
  assertTrue "system is an ec2 instance" "systemIsEc2"
}

testSystemGetMeta() {
  assertFalse "should not get meta if not an ec2 instance" "systemGetMeta instance-id"

  if systemIsEc2; then
    assertTrue "should get instance-id of ec2 instance" "systemGetMeta instance-id"
    assertTrue "should have an \$INSTANCE-ID set" "echo $INSTANCE_ID | egrep '^i-[0-9a-f]{8}$'"

    assertTrue "should get ami-id of ec2 instance" "systemGetMeta ami-id"
    assertTrue "should have an \$AMI-ID set" "echo $AMI_ID | egrep '^ami-[0-9a-f]{8}$'"
  fi
}

oneTimeSetUp() {
  # load include to test
  . ../lib/system.inc
}

SetUp() {
  unset IS_EC2
}


# load and run shUnit2
. ./shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
