#! /bin/sh

testElbMember() {
  INSTANCE_ID="i-aaaaaaaa"
  assertTrue "instance is a member of elb" "elbMember"

  INSTANCE_ID="i-xxxxxxxx"
  assertFalse "instance is not member of elb" "elbMember"

  INSTANCE_ID=""
  assertFalse "instance doesn't know who it is" "elbMember"
}

testElbOutOfService() {
  INSTANCE_ID="i-aaaaaaaa"
  assertTrue "instance is a member of elb" "elbMember"

  INSTANCE_ID="i-xxxxxxxx"
  assertFalse "instance is not member of elb" "elbMember"

  INSTANCE_ID=""
  assertFalse "instance doesn't know who it is" "elbMember"
}

oneTimeSetUp() {
  # load include to test
  . ../lib/elb.inc
  ELB="FAKEELB"
  TMP_FILE=`mktemp -t terminate_test_elb`

  # PRIME THE TMP_FILE
  cat > $TMP_FILE <<EOF
INSTANCE_ID  i-aaaaaaaa  InService  N/A  N/A
INSTANCE_ID  i-bbbbbbbb  InService  N/A  N/A
INSTANCE_ID  i-cccccccc  InService  N/A  N/A
INSTANCE_ID  i-dddddddd  InService  N/A  N/A
EOF

}

oneTimeTearDown() {
  rm -f $TMP_FILE
}

# load and run shUnit2
. ./shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
